# Generated by Django 5.2.15 on 2026-10-02 08:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0128_invite_disciplines'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='release_view',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Release Name')),
                ('version', models.CharField(blank=True, max_length=64)),
                ('description_html', models.TextField(blank=True, default='<p></p>')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('frozen', 'Frozen'), ('released', 'Released'), ('rolled_back', 'Rolled back'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('target_date', models.DateField(null=True)),
                ('released_at', models.DateTimeField(null=True)),
                ('checklist', models.JSONField(default=list)),
                ('sort_order', models.FloatField(default=65535)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('owned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_releases', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Release',
                'verbose_name_plural': 'Releases',
                'db_table': 'releases',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReleaseIssue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('shipped_at', models.DateTimeField(null=True)),
                ('shipped_via', models.CharField(blank=True, max_length=255)),
                ('is_unplanned', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_releases', to='db.issue')),
                ('previous_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='db.state')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_issues', to='db.release')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Release Issue',
                'verbose_name_plural': 'Release Issues',
                'db_table': 'release_issues',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='release',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name', 'project'), name='release_unique_name_project_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='release',
            unique_together={('name', 'project', 'deleted_at')},
        ),
        migrations.AddConstraint(
            model_name='releaseissue',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('release', 'issue'), name='release_issue_unique_release_issue_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='releaseissue',
            unique_together={('release', 'issue', 'deleted_at')},
        ),
    ]
